import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "AI Transparency & Disclosure — KitsuBeat",
  description: "How KitsuBeat uses AI — lesson generation, transcription, and content tools — and what that means for users.",
};

function LegalNavFooter() {
  return (
    <nav
      aria-label="Legal pages"
      className="mt-8 border-t border-[var(--color-border)] pt-6"
    >
      <ul className="flex flex-wrap gap-4 text-sm text-[var(--color-text-muted)]">
        {[
          { href: "/legal/terms", label: "Terms & Conditions" },
          { href: "/legal/privacy", label: "Privacy Policy" },
          { href: "/legal/cookie-policy", label: "Cookie Policy" },
          { href: "/legal/ai-transparency", label: "AI Transparency" },
          { href: "/legal/refund", label: "Refund Policy" },
        ].map(({ href, label }) => (
          <li key={href}>
            <Link
              href={href}
              className="hover:text-[var(--color-accent-readable)] hover:underline"
            >
              {label}
            </Link>
          </li>
        ))}
      </ul>
    </nav>
  );
}

export default function AiTransparencyPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-12 text-[var(--color-text)]">
      <h1 className="text-[28px] font-bold leading-[1.2]">
        AI Transparency &amp; Disclosure
      </h1>
      <p className="mt-2 mb-8 text-sm text-[var(--color-text-muted)]">
        Effective 2026-XX-XX
      </p>
      <hr className="border-[var(--color-border)] my-6" />

      <p className="mt-4 text-[16px] leading-[1.6]">
        KitsuBeat uses artificial intelligence in several parts of the learning
        experience. This page explains where AI is used, what systems are
        involved, and how you can identify AI-generated content.
      </p>

      <section>
        {/* REQ-AI-LESSON-01 */}
        <h2 className="mt-8 mb-3 text-[20px] font-bold leading-[1.3]">
          1. AI-Assisted Lesson Content
        </h2>
        <p className="mt-4 text-[16px] leading-[1.6]">
          Vocabulary definitions, grammar explanations, verse translations, and
          learning mnemonics in KitsuBeat are generated by the{" "}
          <strong>Claude AI model</strong>, developed by Anthropic. This content
          is produced automatically using AI and has been reviewed for quality,
          but it may still contain inaccuracies, especially for:
        </p>
        <ul className="mt-4 list-disc pl-6 text-[16px] leading-[1.6] space-y-2">
          <li>Idiomatic expressions and colloquial usage</li>
          <li>Regional dialect variations</li>
          <li>Nuanced grammatical edge cases</li>
          <li>Song lyrics that are deliberately ambiguous or poetic</li>
        </ul>
        <p className="mt-4 text-[16px] leading-[1.6]">
          We recommend verifying important language information with authoritative
          reference materials such as dictionaries or a qualified Japanese
          language teacher.
        </p>
      </section>

      <section>
        {/* REQ-AI-WHISPER-04 */}
        <h2 className="mt-8 mb-3 text-[20px] font-bold leading-[1.3]">
          2. AI-Generated Transcriptions (WhisperX)
        </h2>
        <p className="mt-4 text-[16px] leading-[1.6]">
          Song transcriptions on KitsuBeat are generated by{" "}
          <strong>WhisperX</strong>, an AI speech-recognition model. These are
          not human transcriptions. WhisperX processes the audio of each song
          to produce time-stamped lyrics.
        </p>
        <p className="mt-4 text-[16px] leading-[1.6]">
          AI transcriptions may contain errors, particularly for:
        </p>
        <ul className="mt-4 list-disc pl-6 text-[16px] leading-[1.6] space-y-2">
          <li>Non-standard pronunciation or heavy vocal effects</li>
          <li>Fast-paced rap or spoken-word sections</li>
          <li>Background noise or complex musical arrangements</li>
          <li>Dialect vocabulary not well represented in training data</li>
        </ul>
        <p className="mt-4 text-[16px] leading-[1.6]">
          Where available, we supplement or correct WhisperX output with
          time-stamped lyrics from LRCLIB, a public-domain lyrics index.
        </p>
      </section>

      <section>
        {/* REQ-AI-WHISPER-03 */}
        <h2 className="mt-8 mb-3 text-[20px] font-bold leading-[1.3]">
          3. Machine-Readable Disclosure
        </h2>
        <p className="mt-4 text-[16px] leading-[1.6]">
          In compliance with emerging AI transparency best practices,
          AI-generated content in KitsuBeat is marked with the HTML attribute{" "}
          <code className="rounded bg-[var(--color-card)] px-1 py-0.5 text-sm">
            data-ai-generated=&quot;true&quot;
          </code>{" "}
          on the relevant components. This allows:
        </p>
        <ul className="mt-4 list-disc pl-6 text-[16px] leading-[1.6] space-y-2">
          <li>
            Screen readers and assistive technologies to identify AI-generated
            content
          </li>
          <li>Browser extensions and accessibility tools to annotate AI content</li>
          <li>
            Programmatic access for researchers or auditors to identify
            AI-generated material
          </li>
        </ul>
      </section>

      <section>
        {/* REQ-AI-LITERACY-01 */}
        <h2 className="mt-8 mb-3 text-[20px] font-bold leading-[1.3]">
          4. Anthropic Claude
        </h2>
        <p className="mt-4 text-[16px] leading-[1.6]">
          The lesson content AI system is Claude, developed by{" "}
          <a
            href="https://www.anthropic.com/claude"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[var(--color-accent-readable)] underline"
          >
            Anthropic
          </a>
          . Anthropic is an AI safety company. KitsuBeat&rsquo;s use of Claude is
          governed by{" "}
          <a
            href="https://www.anthropic.com/legal/usage-policy"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[var(--color-accent-readable)] underline"
          >
            Anthropic&rsquo;s Usage Policies
          </a>
          .
        </p>
        <p className="mt-4 text-[16px] leading-[1.6]">
          Lesson content is generated offline during content preparation — your
          personal learning data and activity are not sent to Anthropic at
          runtime.
        </p>
      </section>

      <section>
        <h2 className="mt-8 mb-3 text-[20px] font-bold leading-[1.3]">
          5. User Control
        </h2>
        <p className="mt-4 text-[16px] leading-[1.6]">
          KitsuBeat clearly labels AI-generated content so you can distinguish
          it from human-authored material:
        </p>
        <ul className="mt-4 list-disc pl-6 text-[16px] leading-[1.6] space-y-2">
          <li>
            Lesson panels show an &ldquo;AI-assisted&rdquo; label on vocabulary definitions,
            grammar explanations, and translations
          </li>
          <li>
            Transcription panels indicate when lyrics are AI-generated by
            WhisperX
          </li>
        </ul>
        <p className="mt-4 text-[16px] leading-[1.6]">
          No AI system makes decisions about your account, access, or progress
          that have legal or similarly significant effects. All content
          recommendations are based on your own spaced-repetition review data.
        </p>
      </section>

      <section>
        <h2 className="mt-8 mb-3 text-[20px] font-bold leading-[1.3]">
          6. Contact
        </h2>
        <p className="mt-4 text-[16px] leading-[1.6]">
          For questions about our use of AI, please contact us at{" "}
          <a
            href="mailto:support@kitsubeat.com"
            className="text-[var(--color-accent-readable)] underline"
          >
            support@kitsubeat.com
          </a>
          .
        </p>
      </section>

      <LegalNavFooter />
    </main>
  );
}
