import type { Metadata } from "next";
import Link from "next/link";
import { CURRENT_TERMS_VERSION, TERMS_EFFECTIVE_DATE } from "@/lib/legal/versions";

export const metadata: Metadata = {
  title: "Terms & Conditions — KitsuBeat",
  description: "Terms and conditions governing use of KitsuBeat, the anime song Japanese learning app.",
};

function LegalNavFooter() {
  return (
    <nav
      aria-label="Legal pages"
      className="mt-8 border-t border-[var(--color-border)] pt-6"
    >
      <ul className="flex flex-wrap gap-4 text-sm text-[var(--color-text-muted)]">
        {[
          { href: "/legal/terms", label: "Terms & Conditions" },
          { href: "/legal/privacy", label: "Privacy Policy" },
          { href: "/legal/cookie-policy", label: "Cookie Policy" },
          { href: "/legal/ai-transparency", label: "AI Transparency" },
          { href: "/legal/refund", label: "Refund Policy" },
        ].map(({ href, label }) => (
          <li key={href}>
            <Link
              href={href}
              className="hover:text-[var(--color-accent-readable)] hover:underline"
            >
              {label}
            </Link>
          </li>
        ))}
      </ul>
    </nav>
  );
}

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-4 py-12 text-[var(--color-text)]">
      <h1 className="text-[28px] font-bold leading-[1.2]">
        Terms &amp; Conditions
      </h1>
      <p className="mt-2 mb-8 text-sm text-[var(--color-text-muted)]">
        Version {CURRENT_TERMS_VERSION} &middot; Effective {TERMS_EFFECTIVE_DATE}
      </p>
      <hr className="border-[var(--color-border)] my-6" />

      <section>
        <h2 className="mt-8 mb-3 text-[20px] font-bold leading-[1.3]">
          1. Acceptance of Terms
        </h2>
        <p className="mt-4 text-[16px] leading-[1.6]">
          By accessing or using KitsuBeat (&ldquo;the Service&rdquo;, &ldquo;we&rdquo;, &ldquo;our&rdquo;),
          you agree to be bound by these Terms &amp; Conditions. If you do not agree with
          any part of these terms, please do not use the Service.
        </p>
        <p className="mt-4 text-[16px] leading-[1.6]">
          Users under the age of 13 may not register for or use the Service.
          Users aged 13–17 require parental or guardian consent to use the Service.
          By registering, you confirm that you meet these age requirements.
        </p>
      </section>

      <section>
        <h2 className="mt-8 mb-3 text-[20px] font-bold leading-[1.3]">
          2. Description of Service
        </h2>
        <p className="mt-4 text-[16px] leading-[1.6]">
          KitsuBeat is a Japanese language learning application that uses music to
          help users acquire vocabulary, grammar, and listening comprehension. The
          Service combines real Japanese songs with AI-assisted learning content,
          spaced-repetition flashcards, and progress tracking.
        </p>
        <p className="mt-4 text-[16px] leading-[1.6]">
          The Service is currently in free beta. Features and availability may
          change at any time without prior notice.
        </p>
      </section>

      <section>
        <h2 className="mt-8 mb-3 text-[20px] font-bold leading-[1.3]">
          3. Copyright &amp; Content
        </h2>
        <p className="mt-4 text-[16px] leading-[1.6]">
          KitsuBeat does not host or distribute audio files. Music is delivered
          exclusively through YouTube&rsquo;s official embed API. No audio is downloaded,
          stored, or redistributed by KitsuBeat.
        </p>
        <p className="mt-4 text-[16px] leading-[1.6]">
          Lyrics data is sourced from LRCLIB, a public-domain time-stamped lyrics
          index. AI-generated transcriptions are produced by the WhisperX
          speech-recognition model and may contain errors. Lesson content —
          including vocabulary definitions, grammar explanations, verse translations,
          and learning mnemonics — is generated by the Claude AI model (Anthropic)
          and has been reviewed but may also contain errors.
        </p>
        <p className="mt-4 text-[16px] leading-[1.6]">
          All original software code, design, and UI elements are copyright
          &copy; KitsuBeat. You may not reproduce, redistribute, or create
          derivative works from our proprietary content without written permission.
        </p>
      </section>

      <section>
        <h2 className="mt-8 mb-3 text-[20px] font-bold leading-[1.3]">
          4. User Accounts
        </h2>
        <p className="mt-4 text-[16px] leading-[1.6]">
          You are responsible for maintaining the confidentiality of your account
          credentials and for all activity that occurs under your account. You must
          notify us immediately of any unauthorised use of your account.
        </p>
        <p className="mt-4 text-[16px] leading-[1.6]">
          We reserve the right to suspend or terminate accounts that violate these
          Terms, engage in abusive behaviour, or misuse the Service.
        </p>
      </section>

      <section>
        <h2 className="mt-8 mb-3 text-[20px] font-bold leading-[1.3]">
          5. Privacy
        </h2>
        <p className="mt-4 text-[16px] leading-[1.6]">
          Your use of the Service is also governed by our{" "}
          <Link
            href="/legal/privacy"
            className="text-[var(--color-accent-readable)] underline"
          >
            Privacy Policy
          </Link>
          , which is incorporated into these Terms by reference. Please read the
          Privacy Policy carefully before using the Service.
        </p>
      </section>

      <section>
        <h2 className="mt-8 mb-3 text-[20px] font-bold leading-[1.3]">
          6. Prohibited Uses
        </h2>
        <p className="mt-4 text-[16px] leading-[1.6]">
          You agree not to:
        </p>
        <ul className="mt-4 list-disc pl-6 text-[16px] leading-[1.6] space-y-2">
          <li>Scrape, crawl, or harvest any content or data from the Service</li>
          <li>Reverse-engineer, decompile, or disassemble any part of the Service</li>
          <li>Use the Service for any unlawful purpose or in violation of any regulations</li>
          <li>Attempt to gain unauthorised access to any system or network connected to the Service</li>
          <li>Transmit any harmful, offensive, or disruptive content</li>
          <li>Impersonate any person or entity</li>
        </ul>
      </section>

      <section>
        <h2 className="mt-8 mb-3 text-[20px] font-bold leading-[1.3]">
          7. Disclaimer
        </h2>
        <p className="mt-4 text-[16px] leading-[1.6]">
          The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of
          any kind, express or implied. We do not warrant that the Service will be
          uninterrupted, error-free, or free of harmful components. AI-generated
          content may contain inaccuracies — always verify important language
          information with authoritative sources.
        </p>
        <p className="mt-4 text-[16px] leading-[1.6]">
          To the maximum extent permitted by applicable law, KitsuBeat shall not
          be liable for any indirect, incidental, special, or consequential damages
          arising from your use of the Service.
        </p>
      </section>

      <section>
        <h2 className="mt-8 mb-3 text-[20px] font-bold leading-[1.3]">
          8. Changes to Terms
        </h2>
        <p className="mt-4 text-[16px] leading-[1.6]">
          We may update these Terms at any time. When we do, we will increment the
          version number above and notify registered users via email. Continued use
          of the Service after changes constitutes acceptance of the updated Terms.
          If you do not agree to the updated Terms, you must stop using the Service.
        </p>
      </section>

      <section>
        <h2 className="mt-8 mb-3 text-[20px] font-bold leading-[1.3]">
          9. Contact
        </h2>
        <p className="mt-4 text-[16px] leading-[1.6]">
          For questions about these Terms, please contact us at{" "}
          <a
            href="mailto:support@kitsubeat.com"
            className="text-[var(--color-accent-readable)] underline"
          >
            support@kitsubeat.com
          </a>
          .
        </p>
      </section>

      <LegalNavFooter />
    </main>
  );
}
