/**
 * 05-insert-db.ts — Upsert all generated content into Neon Postgres.
 *
 * Reads from:
 * - data/songs-manifest.json: metadata (title, artist, anime, etc.)
 * - data/lessons-cache/{slug}.json: lesson JSONB (generated by Plan 04)
 * - data/lyrics-cache/{slug}.json: lyrics_source + synced_lrc (from Plan 02)
 * - data/lyrics-cache/_rejected/{slug}.json: original canonical lyrics if a
 *   past validator REJECT moved them out of the active cache (legacy data —
 *   the validator is now non-destructive and never quarantines)
 * - data/timing-cache/{slug}.json: original WhisperX timing (from Plan 03)
 * - data/timing-cache-stem/{slug}.json: Demucs+WhisperX stem-isolated timing
 *   (preferred when present — mean kCov +0.24 over raw audio)
 *
 * For each song in the manifest:
 * - Upsert shared metadata into songs (title, artist, anime, jlpt_level, …)
 * - Upsert the full-version row into song_versions with lesson, synced_lrc,
 *   timing data, and the dual-source lyrics columns:
 *     - canonical_lyrics: frozen lrclib/genius record
 *     - whisper_lyrics:   frozen WhisperX transcription record
 *   Keyed on (song_id, version_type='full'). TV versions are owned by the
 *   10-prepare-tv.ts / 10c-load-tv-lessons.ts pipeline and are not touched here.
 * - If no lesson cache: skip with warning (lesson not yet generated)
 *
 * Supports upsert: re-running will update existing records without duplicating.
 * Set content_schema_version = 1 on all records.
 *
 * Usage:
 *   npx drizzle-kit push       # Create/sync songs table in Neon first
 *   npx tsx scripts/seed/05-insert-db.ts                 # all songs
 *   npx tsx scripts/seed/05-insert-db.ts --slug=sign-flow         # one song
 *   npx tsx scripts/seed/05-insert-db.ts --slug=sign-flow,fly-higher  # subset
 */

import { config } from "dotenv";
import { readFileSync, existsSync, statSync } from "fs";
import { resolve, join } from "path";
import { fileURLToPath } from "url";

// Load .env.local FIRST — must happen before any DB client is created
// (dotenv config runs synchronously at top of module body, before await/async code)
config({ path: ".env.local" });

import { Pool } from "@neondatabase/serverless";
import { drizzle as drizzlePool } from "drizzle-orm/neon-serverless";
import { songs, songVersions } from "../../src/lib/db/schema.js";
import { SongManifestSchema } from "../types/manifest.js";
import { LessonSchema, type Lesson } from "../types/lesson.js";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const PROJECT_ROOT = resolve(__dirname, "../../");

const MANIFEST_PATH = join(PROJECT_ROOT, "data/songs-manifest.json");
const LESSONS_CACHE_DIR = join(PROJECT_ROOT, "data/lessons-cache");
const LYRICS_CACHE_DIR = join(PROJECT_ROOT, "data/lyrics-cache");
const REJECTED_LYRICS_DIR = join(LYRICS_CACHE_DIR, "_rejected");
const TIMING_CACHE_DIR = join(PROJECT_ROOT, "data/timing-cache");
const TIMING_STEM_DIR = join(PROJECT_ROOT, "data/timing-cache-stem");

const CANONICAL_SOURCES = new Set<string>([
  "lrclib",
  "genius",
  "genius_canonical",
]);

interface TimingCacheEntry {
  slug: string;
  youtube_id: string;
  words?: Array<{
    word: string;
    start: number;
    end: number;
    score: number;
  }>;
  segments?: Array<{
    start: number;
    end: number;
    text: string;
    words?: Array<{ word: string; start: number; end: number; score: number }>;
  }>;
}

interface LyricsCacheEntry {
  slug: string;
  title?: string;
  artist?: string;
  source: string; // "lrclib" | "genius" | "whisper_transcription" | …
  raw_lyrics?: string;
  synced_lrc?: Array<{ startMs: number; text: string }> | null;
}

interface CanonicalLyricsJson {
  source: "lrclib" | "genius" | "genius_canonical";
  raw_lyrics: string;
  synced_lrc: Array<{ startMs: number; text: string }> | null;
  fetched_at: string | null;
}

interface WhisperLyricsJson {
  model: "whisperx-large-v3" | "demucs+whisperx-large-v3";
  raw_lyrics: string;
  words: Array<{ word: string; start: number; end: number; score?: number }>;
  kcov_against_canonical: number | null;
  transcribed_at: string | null;
}

function fileMTime(path: string): string | null {
  try {
    return statSync(path).mtime.toISOString();
  } catch {
    return null;
  }
}

function readJsonOrNull<T>(path: string): T | null {
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, "utf-8")) as T;
  } catch {
    return null;
  }
}

/** Build the canonical_lyrics jsonb from disk. Prefers the quarantined
 *  _rejected/{slug}.json (preserves the lrclib/genius original even if a
 *  past validator REJECT overwrote the active cache); falls back to the
 *  active lyrics-cache when its source is canonical. */
function buildCanonicalLyrics(slug: string): CanonicalLyricsJson | null {
  const rejectedPath = join(REJECTED_LYRICS_DIR, `${slug}.json`);
  const rejected = readJsonOrNull<LyricsCacheEntry>(rejectedPath);
  if (rejected && CANONICAL_SOURCES.has(rejected.source)) {
    return {
      source: rejected.source as CanonicalLyricsJson["source"],
      raw_lyrics: rejected.raw_lyrics ?? "",
      synced_lrc: rejected.synced_lrc ?? null,
      fetched_at: fileMTime(rejectedPath),
    };
  }
  const activePath = join(LYRICS_CACHE_DIR, `${slug}.json`);
  const active = readJsonOrNull<LyricsCacheEntry>(activePath);
  if (active && CANONICAL_SOURCES.has(active.source)) {
    return {
      source: active.source as CanonicalLyricsJson["source"],
      raw_lyrics: active.raw_lyrics ?? "",
      synced_lrc: active.synced_lrc ?? null,
      fetched_at: fileMTime(activePath),
    };
  }
  return null;
}

/** Build the whisper_lyrics jsonb from disk. Prefers Demucs+stem timing when
 *  present (higher kCov), falls back to original raw-audio Whisper. */
function buildWhisperLyrics(slug: string): WhisperLyricsJson | null {
  const stemPath = join(TIMING_STEM_DIR, `${slug}.json`);
  const stem = readJsonOrNull<TimingCacheEntry>(stemPath);
  if (stem && stem.words && stem.words.length > 0) {
    return {
      model: "demucs+whisperx-large-v3",
      raw_lyrics: stem.words.map((w) => w.word).join(""),
      words: stem.words,
      kcov_against_canonical: null,
      transcribed_at: fileMTime(stemPath),
    };
  }
  const origPath = join(TIMING_CACHE_DIR, `${slug}.json`);
  const orig = readJsonOrNull<TimingCacheEntry>(origPath);
  if (orig && orig.words && orig.words.length > 0) {
    return {
      model: "whisperx-large-v3",
      raw_lyrics: orig.words.map((w) => w.word).join(""),
      words: orig.words,
      kcov_against_canonical: null,
      transcribed_at: fileMTime(origPath),
    };
  }
  return null;
}

// ---------------------------------------------------------------------------
// Exported helper — used directly by integration tests
// ---------------------------------------------------------------------------

export interface InsertSongInputs {
  lesson: Lesson;
  lyricsSource: string | null;
  syncedLrc: LyricsCacheEntry["synced_lrc"] | null;
  canonicalLyrics: CanonicalLyricsJson | null;
  whisperLyrics: WhisperLyricsJson | null;
  timingYoutubeId: string | null;
  timingData: TimingCacheEntry | null;
}

/**
 * Upserts one song's `songs` row + `song_versions` row inside a single
 * db.transaction() so a mid-row failure rolls back both writes atomically.
 *
 * Called by the per-song loop in main() and directly by integration tests.
 * Throws on any DB error so the caller's catch block can record the failure.
 */
export async function insertSongTransactional(
  db: ReturnType<typeof drizzlePool>,
  song: {
    slug: string;
    title: string;
    artist: string;
    anime: string;
    season_info?: string | null;
    year_launched?: number | null;
    genre_tags?: string[];
    mood_tags?: string[];
    youtube_id?: string | null;
  },
  inputs: InsertSongInputs,
): Promise<void> {
  const {
    lesson,
    lyricsSource,
    syncedLrc,
    canonicalLyrics,
    whisperLyrics,
    timingYoutubeId,
    timingData,
  } = inputs;

  await db.transaction(async (tx) => {
    // 1. Upsert shared metadata into songs; capture id for the version upsert.
    const [songRow] = await tx
      .insert(songs)
      .values({
        slug: song.slug,
        title: song.title,
        artist: song.artist,
        anime: song.anime,
        season_info: song.season_info ?? null,
        year_launched: song.year_launched ?? null,
        genre_tags: song.genre_tags ?? [],
        mood_tags: song.mood_tags ?? [],
        jlpt_level: lesson.jlpt_level,
        difficulty_tier: lesson.difficulty_tier,
        content_schema_version: 1,
      })
      .onConflictDoUpdate({
        target: songs.slug,
        set: {
          title: song.title,
          artist: song.artist,
          anime: song.anime,
          season_info: song.season_info ?? null,
          year_launched: song.year_launched ?? null,
          genre_tags: song.genre_tags ?? [],
          mood_tags: song.mood_tags ?? [],
          jlpt_level: lesson.jlpt_level,
          difficulty_tier: lesson.difficulty_tier,
          content_schema_version: 1,
          updated_at: new Date(),
        },
      })
      .returning({ id: songs.id });

    if (!songRow) {
      throw new Error("songs upsert returned no row");
    }

    // 2. Upsert the full-version row into song_versions inside the SAME transaction.
    //    TV rows are owned by the 10-prepare-tv pipeline and are intentionally left alone.
    await tx
      .insert(songVersions)
      .values({
        song_id: songRow.id,
        version_type: "full",
        youtube_id: song.youtube_id ?? null,
        lesson: lesson,
        lyrics_source: lyricsSource,
        synced_lrc: syncedLrc as unknown as Record<string, unknown> | null,
        lyrics_offset_ms: 0,
        canonical_lyrics: canonicalLyrics as unknown as Record<string, unknown> | null,
        whisper_lyrics: whisperLyrics as unknown as Record<string, unknown> | null,
        timing_youtube_id: timingYoutubeId,
        timing_data: timingData as unknown as Record<string, unknown> | null,
        timing_verified: "auto",
      })
      .onConflictDoUpdate({
        target: [songVersions.song_id, songVersions.version_type],
        set: {
          youtube_id: song.youtube_id ?? null,
          lesson: lesson,
          lyrics_source: lyricsSource,
          synced_lrc: syncedLrc as unknown as Record<string, unknown> | null,
          canonical_lyrics: canonicalLyrics as unknown as Record<string, unknown> | null,
          whisper_lyrics: whisperLyrics as unknown as Record<string, unknown> | null,
          timing_youtube_id: timingYoutubeId,
          timing_data: timingData as unknown as Record<string, unknown> | null,
          updated_at: new Date(),
        },
      });
  });
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  console.log("=== 05-insert-db: Upsert Songs into Neon Postgres ===\n");

  const slugArg = process.argv.find((a) => a.startsWith("--slug="));
  const onlySlugs = slugArg
    ? new Set(slugArg.slice("--slug=".length).split(",").map((s) => s.trim()).filter(Boolean))
    : null;

  // 1. Load manifest
  if (!existsSync(MANIFEST_PATH)) {
    console.error(`ERROR: songs-manifest.json not found at ${MANIFEST_PATH}`);
    console.error("Run scripts/seed/01-build-manifest.ts first.");
    process.exit(1);
  }
  const manifestRaw = JSON.parse(readFileSync(MANIFEST_PATH, "utf-8"));
  const fullManifest = SongManifestSchema.parse(manifestRaw);
  const manifest = onlySlugs
    ? fullManifest.filter((s) => onlySlugs.has(s.slug))
    : fullManifest;
  if (onlySlugs) {
    console.log(`  Loaded manifest: ${manifest.length}/${fullManifest.length} songs (filter: ${[...onlySlugs].join(", ")})`);
    const missing = [...onlySlugs].filter((s) => !manifest.some((m) => m.slug === s));
    if (missing.length > 0) {
      console.error(`  ERROR: --slug values not in manifest: ${missing.join(", ")}`);
      process.exit(1);
    }
  } else {
    console.log(`  Loaded manifest: ${manifest.length} songs`);
  }

  // 2. Initialise script-local WebSocket pool (required for db.transaction()).
  //    The app's getDb() returns NeonHttpDatabase which does NOT support callback
  //    transactions — the WebSocket pool is the only viable path (D-04 + PATTERNS.md).
  if (!process.env.DATABASE_URL) {
    throw new Error("DATABASE_URL is not set in .env.local — required for WebSocket pool.");
  }
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  const db = drizzlePool(pool);

  // 3. Process each song
  let insertedCount = 0;
  let updatedCount = 0;
  let skippedCount = 0;
  let errorCount = 0;
  const failedSlugs: string[] = [];

  try {
  for (const song of manifest) {
    const lessonPath = join(LESSONS_CACHE_DIR, `${song.slug}.json`);
    const timingPath = join(TIMING_CACHE_DIR, `${song.slug}.json`);

    // Skip if no lesson cache
    if (!existsSync(lessonPath)) {
      console.log(`  [SKIP] ${song.slug} — no lesson cache`);
      skippedCount++;
      continue;
    }

    // Load and validate lesson
    let lesson: Lesson;
    try {
      const lessonRaw = JSON.parse(readFileSync(lessonPath, "utf-8"));
      const parsed = LessonSchema.safeParse(lessonRaw);
      if (!parsed.success) {
        console.warn(
          `  [ERROR] ${song.slug} — lesson validation failed: ${parsed.error.errors[0]?.message}`
        );
        errorCount++;
        continue;
      }
      lesson = parsed.data;
    } catch (err) {
      console.warn(`  [ERROR] ${song.slug} — failed to read lesson: ${(err as Error).message}`);
      errorCount++;
      continue;
    }

    // Load timing data (optional — may not exist for all songs)
    let timingData: TimingCacheEntry | null = null;
    let timingYoutubeId: string | null = null;
    if (existsSync(timingPath)) {
      try {
        timingData = JSON.parse(readFileSync(timingPath, "utf-8")) as TimingCacheEntry;
        timingYoutubeId = timingData.youtube_id ?? null;
      } catch {
        console.warn(`  [WARN] ${song.slug} — failed to read timing cache, continuing without timing data`);
      }
    }

    // Load lyrics cache (optional — provides lyrics_source + synced_lrc for the full version)
    const lyricsPath = join(LYRICS_CACHE_DIR, `${song.slug}.json`);
    let lyricsSource: string | null = null;
    let syncedLrc: LyricsCacheEntry["synced_lrc"] | null = null;
    if (existsSync(lyricsPath)) {
      try {
        const lyricsCache = JSON.parse(readFileSync(lyricsPath, "utf-8")) as LyricsCacheEntry;
        lyricsSource = lyricsCache.source ?? null;
        syncedLrc = lyricsCache.synced_lrc ?? null;
      } catch {
        console.warn(`  [WARN] ${song.slug} — failed to read lyrics cache, continuing without synced lyrics`);
      }
    }

    // Build the dual-source jsonb columns (drizzle/0013_dual_source_lyrics).
    // These preserve both the canonical lrclib/genius record AND the WhisperX
    // transcription regardless of which one is currently active.
    const canonicalLyrics = buildCanonicalLyrics(song.slug);
    const whisperLyrics = buildWhisperLyrics(song.slug);

    try {
      await insertSongTransactional(db, song, {
        lesson,
        lyricsSource,
        syncedLrc,
        canonicalLyrics,
        whisperLyrics,
        timingYoutubeId,
        timingData,
      });

      // Phase 13 D-02: invalidate the cached song page for this slug so the next
      // /songs/[slug] request re-fetches the updated lesson body. Dynamic import
      // matches the lazy-DB-import pattern used elsewhere in seed scripts.
      try {
        const { revalidateSongCache } = await import("../../src/app/actions/cache.js");
        await revalidateSongCache(song.slug);
      } catch (revalErr) {
        process.stderr.write(
          `  [WARN] ${song.slug} — revalidate failed: ${(revalErr as Error).message}\n`
        );
        // Do not abort the batch — upsert succeeded; operator can revalidate manually.
      }

      insertedCount++;
      process.stdout.write(`  [OK] ${song.slug} — upserted\n`);
    } catch (err) {
      // D-05 locked stderr format — emit ONLY slug + message, never connection string / stack.
      console.error(`[insert-fail] slug=${song.slug} error=${(err as Error).message}`);
      failedSlugs.push(song.slug);
      errorCount++;
    }
  }
  } finally {
    await pool.end();
  }

  // Summary
  console.log("\n=== Results ===");
  console.log(`  Upserted: ${insertedCount}`);
  console.log(`  Skipped (no lesson): ${skippedCount}`);
  console.log(`  Errors: ${errorCount}`);
  console.log(`  Total manifest songs: ${manifest.length}`);
  console.log("\nDone.");

  // D-05 end-of-run failure summary (SPEC AC #9)
  if (failedSlugs.length > 0) {
    console.error(`\n${failedSlugs.length} songs failed: ${failedSlugs.join(", ")}`);
  }
  // Non-zero exit ONLY if every song failed — overnight pipelines value partial
  // progress over zero progress (SPEC AC #9).
  if (manifest.length > 0 && failedSlugs.length === manifest.length) {
    process.exit(1);
  }
}

// Guard: only invoke main() when this file is the direct entry point (not imported).
// Without this guard, test imports trigger main() against the dev DB (Rule-2 fix).
//
// tsx invokes the script by setting process.argv[1] to the .ts file path.
// When imported by Vitest, process.argv[1] points to the vitest runner binary.
// We compare the base filenames (no extension) to handle tsx's in-memory transform.
const _selfBasename = fileURLToPath(import.meta.url)
  .replace(/\\/g, "/")
  .split("/")
  .pop()
  ?.replace(/\.[cm]?[jt]s$/, "") ?? "";
const _entryBasename = (process.argv[1] ?? "")
  .replace(/\\/g, "/")
  .split("/")
  .pop()
  ?.replace(/\.[cm]?[jt]s$/, "") ?? "";

if (_selfBasename && _selfBasename === _entryBasename) {
  main().catch((err) => {
    console.error("Fatal error:", err);
    process.exit(1);
  });
}
