/**
 * 05-insert-db.ts — Upsert all generated content into Neon Postgres.
 *
 * Reads from:
 * - data/songs-manifest.json: metadata (title, artist, anime, etc.)
 * - data/lessons-cache/{slug}.json: lesson JSONB (generated by Plan 04)
 * - data/timing-cache/{slug}.json: timing_data JSONB + timing_youtube_id (from Plan 03)
 *
 * For each song in the manifest:
 * - If lesson cache exists: upsert full record into songs table
 * - If no lesson cache: skip with warning (lesson not yet generated)
 * - Timing data is included if available; null otherwise
 *
 * Supports upsert: re-running will update existing records without duplicating.
 * Set content_schema_version = 1 on all records.
 *
 * Usage:
 *   npx drizzle-kit push       # Create/sync songs table in Neon first
 *   npx tsx scripts/seed/05-insert-db.ts
 */

import { config } from "dotenv";
import { readFileSync, existsSync } from "fs";
import { resolve, join } from "path";
import { fileURLToPath } from "url";

// Load .env.local FIRST — must happen before getDb() is called
// (dotenv config runs synchronously at top of module body, before await/async code)
config({ path: ".env.local" });

import { getDb } from "../../src/lib/db/index.js";
import { songs } from "../../src/lib/db/schema.js";
import { SongManifestSchema } from "../types/manifest.js";
import { LessonSchema, type Lesson } from "../types/lesson.js";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const PROJECT_ROOT = resolve(__dirname, "../../");

const MANIFEST_PATH = join(PROJECT_ROOT, "data/songs-manifest.json");
const LESSONS_CACHE_DIR = join(PROJECT_ROOT, "data/lessons-cache");
const TIMING_CACHE_DIR = join(PROJECT_ROOT, "data/timing-cache");

interface TimingCacheEntry {
  slug: string;
  youtube_id: string;
  words?: Array<{
    word: string;
    start: number;
    end: number;
    score: number;
  }>;
  segments?: Array<{
    start: number;
    end: number;
    text: string;
    words?: Array<{ word: string; start: number; end: number; score: number }>;
  }>;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  console.log("=== 05-insert-db: Upsert Songs into Neon Postgres ===\n");

  // 1. Load manifest
  if (!existsSync(MANIFEST_PATH)) {
    console.error(`ERROR: songs-manifest.json not found at ${MANIFEST_PATH}`);
    console.error("Run scripts/seed/01-build-manifest.ts first.");
    process.exit(1);
  }
  const manifestRaw = JSON.parse(readFileSync(MANIFEST_PATH, "utf-8"));
  const manifest = SongManifestSchema.parse(manifestRaw);
  console.log(`  Loaded manifest: ${manifest.length} songs`);

  // 2. Process each song
  let insertedCount = 0;
  let updatedCount = 0;
  let skippedCount = 0;
  let errorCount = 0;

  for (const song of manifest) {
    const lessonPath = join(LESSONS_CACHE_DIR, `${song.slug}.json`);
    const timingPath = join(TIMING_CACHE_DIR, `${song.slug}.json`);

    // Skip if no lesson cache
    if (!existsSync(lessonPath)) {
      console.log(`  [SKIP] ${song.slug} — no lesson cache`);
      skippedCount++;
      continue;
    }

    // Load and validate lesson
    let lesson: Lesson;
    try {
      const lessonRaw = JSON.parse(readFileSync(lessonPath, "utf-8"));
      const parsed = LessonSchema.safeParse(lessonRaw);
      if (!parsed.success) {
        console.warn(
          `  [ERROR] ${song.slug} — lesson validation failed: ${parsed.error.errors[0]?.message}`
        );
        errorCount++;
        continue;
      }
      lesson = parsed.data;
    } catch (err) {
      console.warn(`  [ERROR] ${song.slug} — failed to read lesson: ${(err as Error).message}`);
      errorCount++;
      continue;
    }

    // Load timing data (optional — may not exist for all songs)
    let timingData: TimingCacheEntry | null = null;
    let timingYoutubeId: string | null = null;
    if (existsSync(timingPath)) {
      try {
        timingData = JSON.parse(readFileSync(timingPath, "utf-8")) as TimingCacheEntry;
        timingYoutubeId = timingData.youtube_id ?? null;
      } catch {
        console.warn(`  [WARN] ${song.slug} — failed to read timing cache, continuing without timing data`);
      }
    }

    // Upsert into songs table
    try {
      const db = getDb();
      await db
        .insert(songs)
        .values({
          slug: song.slug,
          title: song.title,
          artist: song.artist,
          anime: song.anime,
          season_info: song.season_info ?? null,
          youtube_id: song.youtube_id ?? null,
          year_launched: song.year_launched ?? null,
          genre_tags: song.genre_tags ?? [],
          mood_tags: song.mood_tags ?? [],
          jlpt_level: lesson.jlpt_level,
          difficulty_tier: lesson.difficulty_tier,
          lesson: lesson,
          lyrics_source: null, // populated by 02-fetch-lyrics if needed
          content_schema_version: 1,
          timing_youtube_id: timingYoutubeId,
          timing_data: timingData as unknown as Record<string, unknown> | null,
          timing_verified: "auto",
        })
        .onConflictDoUpdate({
          target: songs.slug,
          set: {
            title: song.title,
            artist: song.artist,
            anime: song.anime,
            season_info: song.season_info ?? null,
            youtube_id: song.youtube_id ?? null,
            year_launched: song.year_launched ?? null,
            genre_tags: song.genre_tags ?? [],
            mood_tags: song.mood_tags ?? [],
            jlpt_level: lesson.jlpt_level,
            difficulty_tier: lesson.difficulty_tier,
            lesson: lesson,
            content_schema_version: 1,
            timing_youtube_id: timingYoutubeId,
            timing_data: timingData as unknown as Record<string, unknown> | null,
            updated_at: new Date(),
          },
        });

      // Determine if this was an insert or update by checking if it was pre-existing
      // (For simplicity we track both as upserted; drizzle doesn't return insert vs update)
      insertedCount++;
      process.stdout.write(`  [OK] ${song.slug} — upserted\n`);
    } catch (err) {
      console.error(`  [ERROR] ${song.slug} — DB upsert failed: ${(err as Error).message}`);
      errorCount++;
    }
  }

  // Summary
  console.log("\n=== Results ===");
  console.log(`  Upserted: ${insertedCount}`);
  console.log(`  Skipped (no lesson): ${skippedCount}`);
  console.log(`  Errors: ${errorCount}`);
  console.log(`  Total manifest songs: ${manifest.length}`);
  console.log("\nDone.");
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
