/**
 * apply-geo-replacements.ts — Persist the picks from data/geo-replacements.json.
 *
 * Reads the proposals generated by find-geo-replacements.ts and flips the
 * youtube_id in three places for every accepted pick:
 *   1. data/songs-manifest.json                    (authoritative metadata)
 *   2. data/songs-manifest-pending-whisper.json    (WhisperX batch queue)
 *   3. song_versions (Neon — drives /songs)
 *
 * Two acceptance modes:
 *   — FULL (default): accept when full_pick.duration >= MIN_FULL_SEC.
 *                     Routes to song_versions.version_type='full'.
 *   — TV-ONLY (--allow-tv-only): accept slugs lacking a usable full_pick but
 *                     carrying a tv_pick with duration in [MIN_TV_SEC,
 *                     MAX_TV_SEC]. Routes to song_versions.version_type='tv'
 *                     and records the slug in data/tv-only-slugs.json so
 *                     downstream scripts (lesson gen, 05-insert-db) know to
 *                     treat the full-length pipeline as not applicable.
 *
 * On the DB row we reset timing_data, timing_youtube_id, and lyrics_offset_ms
 * so the WhisperX pipeline re-keys them cleanly to the new video. synced_lrc
 * is retained because it tracks the audio master, not the video (the TV-only
 * case will override via truncated lyrics at lesson-gen time).
 *
 * Rejected proposals (no usable pick in either mode) are removed from the
 * pending-whisper queue so WhisperX doesn't waste cycles on geo-blocked URLs.
 *
 * Usage:
 *   npx tsx --tsconfig tsconfig.scripts.json scripts/seed/apply-geo-replacements.ts
 *   npx tsx --tsconfig tsconfig.scripts.json scripts/seed/apply-geo-replacements.ts --dry-run
 *   npx tsx --tsconfig tsconfig.scripts.json scripts/seed/apply-geo-replacements.ts --allow-tv-only
 */

import { config } from "dotenv";
config({ path: ".env.local" });

import { readFileSync, writeFileSync, existsSync } from "fs";
import { resolve, join } from "path";
import { fileURLToPath } from "url";
import { and, eq } from "drizzle-orm";

import { getDb } from "../../src/lib/db/index.js";
import { songs, songVersions } from "../../src/lib/db/schema.js";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const PROJECT_ROOT = resolve(__dirname, "../../");

const MANIFEST_PATH = join(PROJECT_ROOT, "data/songs-manifest.json");
const PENDING_MANIFEST_PATH = join(PROJECT_ROOT, "data/songs-manifest-pending-whisper.json");
const GEO_PATH = join(PROJECT_ROOT, "data/geo-replacements.json");
const TV_ONLY_REGISTRY_PATH = join(PROJECT_ROOT, "data/tv-only-slugs.json");

// A "full" video we trust; anything shorter is almost certainly a TV cut.
const MIN_FULL_SEC = 150;
// TV-cut band matches find-geo-replacements.ts — reject snippets and over-long
// lyric videos that would break the TV lesson assumption (~90s runtime).
const MIN_TV_SEC = 60;
const MAX_TV_SEC = 150;

const DRY_RUN = process.argv.includes("--dry-run");
const ALLOW_TV_ONLY = process.argv.includes("--allow-tv-only");

interface Pick {
  id: string;
  channel: string;
  duration: number;
  title: string;
}
interface GeoResult {
  slug: string;
  current_youtube_id: string;
  full_pick: Pick | null;
  tv_pick: Pick | null;
}
interface GeoFile {
  generated_at: string;
  results: GeoResult[];
}
interface ManifestEntry {
  slug: string;
  youtube_id: string | null;
  [k: string]: unknown;
}
type Bucket = "full" | "tv" | "skip";

function classify(r: GeoResult): { bucket: Bucket; pick: Pick | null } {
  if (r.full_pick && r.full_pick.duration >= MIN_FULL_SEC) {
    return { bucket: "full", pick: r.full_pick };
  }
  if (
    ALLOW_TV_ONLY &&
    r.tv_pick &&
    r.tv_pick.duration >= MIN_TV_SEC &&
    r.tv_pick.duration <= MAX_TV_SEC
  ) {
    return { bucket: "tv", pick: r.tv_pick };
  }
  return { bucket: "skip", pick: null };
}

function readTvOnlyRegistry(): Set<string> {
  if (!existsSync(TV_ONLY_REGISTRY_PATH)) return new Set();
  try {
    const arr = JSON.parse(readFileSync(TV_ONLY_REGISTRY_PATH, "utf-8")) as string[];
    return new Set(arr);
  } catch {
    return new Set();
  }
}

async function main(): Promise<void> {
  const mode = ALLOW_TV_ONLY ? "APPLY + TV-ONLY" : "APPLY (full only)";
  console.log(`=== apply-geo-replacements (${DRY_RUN ? `DRY RUN — ${mode}` : mode}) ===\n`);

  const geo = JSON.parse(readFileSync(GEO_PATH, "utf-8")) as GeoFile;
  const classified = geo.results.map((r) => ({ result: r, ...classify(r) }));
  const applyFull = classified.filter((c) => c.bucket === "full");
  const applyTv = classified.filter((c) => c.bucket === "tv");
  const toSkip = classified.filter((c) => c.bucket === "skip");

  console.log(`Proposals: ${geo.results.length}`);
  console.log(`  apply FULL (>= ${MIN_FULL_SEC}s):               ${applyFull.length}`);
  console.log(`  apply TV   (${MIN_TV_SEC}-${MAX_TV_SEC}s, only when --allow-tv-only): ${applyTv.length}`);
  console.log(`  skip       (no usable pick):                  ${toSkip.length}`);
  for (const c of toSkip) {
    const r = c.result;
    const reason = r.full_pick
      ? `full_pick=${r.full_pick.id} dur=${r.full_pick.duration}s <${MIN_FULL_SEC}` +
        (r.tv_pick ? `; tv_pick=${r.tv_pick.id} dur=${r.tv_pick.duration}s (pass --allow-tv-only to accept)` : "; no tv_pick")
      : r.tv_pick
        ? `tv_pick=${r.tv_pick.id} dur=${r.tv_pick.duration}s (pass --allow-tv-only to accept)`
        : "no full_pick and no tv_pick";
    console.log(`    - ${r.slug}  (${reason})`);
  }
  console.log();

  if (applyFull.length === 0 && applyTv.length === 0) {
    console.log("Nothing to apply. Exiting.");
    return;
  }

  // ── 1. Update songs-manifest.json — sets the canonical youtube_id for both
  //    buckets. The TV-only bucket stores the TV id because the manifest has
  //    only one youtube_id field; the registry file records which slugs are
  //    TV-only so downstream code doesn't misinterpret it as a full video.
  const manifest = JSON.parse(readFileSync(MANIFEST_PATH, "utf-8")) as ManifestEntry[];
  const bySlug = new Map(manifest.map((e) => [e.slug, e]));
  let manifestUpdates = 0;
  for (const c of [...applyFull, ...applyTv]) {
    const entry = bySlug.get(c.result.slug);
    if (!entry) {
      console.warn(`  [WARN] ${c.result.slug} — not in main manifest, skipping`);
      continue;
    }
    if (entry.youtube_id === c.pick!.id) continue;
    entry.youtube_id = c.pick!.id;
    manifestUpdates++;
  }
  if (!DRY_RUN && manifestUpdates > 0) {
    writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2) + "\n", "utf-8");
  }
  console.log(`[manifest]        ${manifestUpdates} youtube_id updates ${DRY_RUN ? "(not written)" : "written"}`);

  // ── 2. Update songs-manifest-pending-whisper.json. All accepted picks stay
  //    in the queue with their new id; skipped slugs are dropped to save
  //    download attempts.
  const pending = JSON.parse(readFileSync(PENDING_MANIFEST_PATH, "utf-8")) as ManifestEntry[];
  const applyMap = new Map([...applyFull, ...applyTv].map((c) => [c.result.slug, c.pick!.id]));
  const dropSet = new Set(toSkip.map((c) => c.result.slug));

  let pendingSwaps = 0;
  let pendingDrops = 0;
  const nextPending: ManifestEntry[] = [];
  for (const entry of pending) {
    if (dropSet.has(entry.slug)) {
      pendingDrops++;
      continue;
    }
    const newId = applyMap.get(entry.slug);
    if (newId && entry.youtube_id !== newId) {
      entry.youtube_id = newId;
      pendingSwaps++;
    }
    nextPending.push(entry);
  }
  if (!DRY_RUN && (pendingSwaps > 0 || pendingDrops > 0)) {
    writeFileSync(PENDING_MANIFEST_PATH, JSON.stringify(nextPending, null, 2) + "\n", "utf-8");
  }
  console.log(
    `[pending-whisper] ${pendingSwaps} swaps, ${pendingDrops} drops ${DRY_RUN ? "(not written)" : "written"}  (queue: ${pending.length} → ${nextPending.length})`
  );

  // ── 3. Update the TV-only registry — add slugs entering TV-only mode, and
  //    remove any slugs that just graduated from TV-only to full coverage.
  const registry = readTvOnlyRegistry();
  const registryBefore = registry.size;
  for (const c of applyTv) registry.add(c.result.slug);
  for (const c of applyFull) registry.delete(c.result.slug);
  const registryAfter = registry.size;
  if (!DRY_RUN && registryBefore !== registryAfter) {
    writeFileSync(
      TV_ONLY_REGISTRY_PATH,
      JSON.stringify([...registry].sort(), null, 2) + "\n",
      "utf-8"
    );
  }
  console.log(`[tv-only-registry] ${registryBefore} → ${registryAfter} slugs ${DRY_RUN ? "(not written)" : "written"}`);

  // ── 4. Update song_versions. FULL picks update (not insert) the existing
  //    'full' row; the row is created by 05-insert-db.ts when a lesson exists.
  //    TV picks upsert a 'tv' row because no earlier pipeline step creates it
  //    for TV-only songs.
  let dbFullUpdates = 0;
  let dbTvUpserts = 0;
  let dbMissing = 0;
  if (!DRY_RUN) {
    const db = getDb();

    for (const c of applyFull) {
      const rows = await db
        .select({ id: songs.id })
        .from(songs)
        .where(eq(songs.slug, c.result.slug));
      const songRow = rows[0];
      if (!songRow) {
        console.log(`  [db miss]  ${c.result.slug} — not in songs table; skipping DB update`);
        dbMissing++;
        continue;
      }
      await db
        .update(songVersions)
        .set({
          youtube_id: c.pick!.id,
          timing_data: null,
          timing_youtube_id: null,
          lyrics_offset_ms: 0,
          updated_at: new Date(),
        })
        .where(
          and(
            eq(songVersions.song_id, songRow.id),
            eq(songVersions.version_type, "full")
          )
        );
      dbFullUpdates++;
    }

    for (const c of applyTv) {
      const rows = await db
        .select({ id: songs.id })
        .from(songs)
        .where(eq(songs.slug, c.result.slug));
      const songRow = rows[0];
      if (!songRow) {
        console.log(`  [db miss]  ${c.result.slug} — not in songs table; skipping TV upsert`);
        dbMissing++;
        continue;
      }
      await db
        .insert(songVersions)
        .values({
          song_id: songRow.id,
          version_type: "tv",
          youtube_id: c.pick!.id,
          lyrics_offset_ms: 0,
          timing_verified: "auto",
        })
        .onConflictDoUpdate({
          target: [songVersions.song_id, songVersions.version_type],
          set: {
            youtube_id: c.pick!.id,
            timing_data: null,
            timing_youtube_id: null,
            updated_at: new Date(),
          },
        });
      dbTvUpserts++;
    }
  }
  console.log(
    `[song_versions]  full=${dbFullUpdates} updates, tv=${dbTvUpserts} upserts${dbMissing ? `, ${dbMissing} skipped (no songs row)` : ""}${DRY_RUN ? " (dry run — skipped)" : ""}`
  );

  console.log("\n=== Summary ===");
  console.log(`  applied full:  ${applyFull.length}`);
  console.log(`  applied tv:    ${applyTv.length}  (${ALLOW_TV_ONLY ? "--allow-tv-only ON" : "--allow-tv-only OFF; none accepted"})`);
  console.log(`  skipped:       ${toSkip.length}  (dropped from pending-whisper queue)`);
  if (DRY_RUN) console.log("\n(DRY RUN — re-run without --dry-run to persist)");
  else console.log("\nDone.");
}

main().catch((err) => {
  console.error("Fatal:", err);
  process.exit(1);
});
