#!/usr/bin/env npx tsx --tsconfig tsconfig.scripts.json
/**
 * Instagram Reels quality improvement loop.
 *
 * Five agents per iteration:
 *   1. Sampler    — pulls live examples from catalog.json + social-queue.json
 *   2. QualityBot — grades posts on content/music/captions/thumbnails/virality/popularity (0-10)
 *   3. RelevanceBot — grades mission alignment (0-10)
 *   4. Improver   — synthesises grade reports → specific code changes
 *   5. Implementer — applies changes to generate-social-queue.ts; regenerates queue
 *
 * Loop exits when quality > 9.0 AND relevance > 6.0, or MAX_ITER reached.
 *
 * Run: npx tsx --tsconfig tsconfig.scripts.json scripts/social/quality-loop.ts
 */

import Anthropic from "@anthropic-ai/sdk";
import { execSync } from "child_process";
import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import { config } from "dotenv";

config({ path: ".env.local" });

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "../..");

const ai = new Anthropic();
const MODEL = "claude-sonnet-4-6";
const MAX_ITER = 8;
const QUALITY_MIN = 9.0;
const RELEVANCE_MIN = 6.0;

// ─── Types ────────────────────────────────────────────────────────────────────

type GradeResult = {
  total: number;
  breakdown: Record<string, number>;
  strengths: string[];
  weaknesses: string[];
  improvements: string[];
  gaps?: string[];
};

type Change = {
  description: string;
  file: string;
  old_text: string;
  new_text: string;
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

function parseJson<T>(text: string, fallback: T): T {
  try {
    // Strip markdown fences if present
    const cleaned = text.replace(/^```json\s*/i, "").replace(/^```\s*/i, "").replace(/\s*```$/i, "").trim();
    return JSON.parse(cleaned) as T;
  } catch {
    console.error("  ⚠ JSON parse failed. Raw:", text.slice(0, 300));
    return fallback;
  }
}

// ─── Agent 1: Sampler ─────────────────────────────────────────────────────────

function samplePosts(): string {
  const catalog = JSON.parse(readFileSync(join(ROOT, "videos/catalog.json"), "utf8"));
  const queue = JSON.parse(readFileSync(join(ROOT, "src/data/social-queue.json"), "utf8"));

  // Three Instagram Reel examples (quiz videos) — one per major series
  const reels = ["one-piece", "naruto", "demon-slayer"].map(key => {
    const s = catalog[key];
    const p = s.parts[0];
    return {
      series: s.label,
      words: p.words,
      tiktok_sound: s.tiktok_sound,
      instagram_caption: p.social?.instagram?.caption ?? "N/A",
      youtube_title: p.social?.youtube?.title ?? "N/A",
      hashtag_count: (p.social?.instagram?.caption ?? "").split("#").length - 1,
    };
  });

  // X/Twitter thread examples (generated by generate-social-queue.ts)
  const vocabEx = queue.queue.find((e: Record<string, unknown>) => e.type === "vocab");
  const quizEx  = queue.queue.find((e: Record<string, unknown>) => e.type === "quiz");

  return JSON.stringify(
    { instagram_reels: reels, x_vocab_thread: vocabEx, x_quiz_thread: quizEx },
    null, 2
  );
}

// ─── Agent 2: Quality Grade ───────────────────────────────────────────────────

async function gradeQuality(posts: string): Promise<GradeResult> {
  const msg = await ai.messages.create({
    model: MODEL,
    max_tokens: 1024,
    messages: [{
      role: "user",
      content: `You are a social media growth expert specialising in language-learning apps and anime content.

Grade the following KitsuBeat Instagram Reels + X posts on a 0–10 scale (target: >9).

Scoring breakdown (must sum to total):
• content  (0–2): word selection quality, educational clarity, scene-context richness, quiz design
• music    (0–2): OST/sound match to anime emotion, energy fit, trending potential
• captions (0–2): hook power (first 2 lines = what users see before tapping "more"), hashtag mix (niche + medium + broad), CTA engagement quality
• thumbnails (0–1): cover design — text hierarchy, brand colour, scroll-stop potential
• virality (0–2): challenge mechanics, "drop your score" comment bait, share triggers, tag-a-friend angles, quiz curiosity gap
• popularity (0–1): trending anime coverage, hashtag discoverability, cross-series appeal

Return ONLY valid JSON, no prose, no fences:
{"total":<0-10>,"breakdown":{"content":<0-2>,"music":<0-2>,"captions":<0-2>,"thumbnails":<0-1>,"virality":<0-2>,"popularity":<0-1>},"strengths":["...","..."],"weaknesses":["...","...","..."],"improvements":["specific actionable fix 1","fix 2","fix 3"]}

Posts to grade:
${posts}`,
    }],
  });
  const text = msg.content[0].type === "text" ? msg.content[0].text : "{}";
  return parseJson<GradeResult>(text, { total: 0, breakdown: {}, strengths: [], weaknesses: [], improvements: [] });
}

// ─── Agent 3: Relevance Grade ─────────────────────────────────────────────────

async function gradeRelevance(posts: string): Promise<GradeResult> {
  const msg = await ai.messages.create({
    model: MODEL,
    max_tokens: 1024,
    messages: [{
      role: "user",
      content: `You are evaluating KitsuBeat's posts for mission alignment. Target: >6/10.

KitsuBeat mission: Help anime fans learn Japanese vocab through shows they already love, using FSRS spaced-repetition so words stick in 3 sessions not 30.

Target audience: Anime fans curious about Japanese but deterred by boring study. They binge anime, love the culture, feel language learning is too hard.

Brand pillars:
1. Every word tied to a scene the user knows emotionally
2. FSRS = scientifically-timed review, no grinding
3. Free to start — immediate value

Grade 0–10 (must sum to total):
• japanese_learning (0–3): are words taught clearly with context and meaning?
• app_discovery     (0–2): is FSRS/app benefit communicated authentically? CTA invites trial naturally?
• audience_fit      (0–2): tone feels native to anime fans, not like a language school?
• authenticity      (0–1.5): content feels earned and genuine, not gimmicky?
• value_prop        (0–1.5): "learn through anime you love" benefit clear and compelling?

Return ONLY valid JSON, no prose, no fences:
{"total":<0-10>,"breakdown":{"japanese_learning":<0-3>,"app_discovery":<0-2>,"audience_fit":<0-2>,"authenticity":<0-1.5>,"value_prop":<0-1.5>},"strengths":["..."],"gaps":["...","..."],"improvements":["specific fix 1","fix 2","fix 3"]}

Posts to evaluate:
${posts}`,
    }],
  });
  const text = msg.content[0].type === "text" ? msg.content[0].text : "{}";
  return parseJson<GradeResult>(text, { total: 0, breakdown: {}, strengths: [], weaknesses: [], improvements: [], gaps: [] });
}

// ─── Agent 4: Improve ─────────────────────────────────────────────────────────

async function synthesise(q: GradeResult, r: GradeResult, posts: string): Promise<Change[]> {
  const code = readFileSync(join(ROOT, "scripts/social/generate-social-queue.ts"), "utf8");

  const msg = await ai.messages.create({
    model: MODEL,
    max_tokens: 4096,
    messages: [{
      role: "user",
      content: `You are a TypeScript developer improving KitsuBeat's social post generation.

QUALITY REPORT  total=${q.total}/10 (target >9)
Weaknesses: ${q.weaknesses.join(" | ")}
Needed:     ${q.improvements.join(" | ")}

RELEVANCE REPORT  total=${r.total}/10 (target >6)
Gaps:    ${(r.gaps ?? []).join(" | ")}
Needed:  ${r.improvements.join(" | ")}

CURRENT SAMPLED POSTS (what we're trying to improve):
${posts}

FILE: scripts/social/generate-social-queue.ts
${code}

Produce 4–6 high-impact changes to the TypeScript file above that will meaningfully raise BOTH scores.

Focus areas (in priority order):
1. VOCAB_HOOK_TEMPLATES — make hooks more curiosity-gap / revelation-first ("Most X fans can't…" > "Do you know…")
2. QUIZ_HOOK_SINGLE_ANIME + QUIZ_HOOK_MULTI_ANIME — add viral challenge framing, score-reporting bait
3. VOCAB_ENGAGE / QUIZ_ENGAGE / ARTICLE_ENGAGE — tighter FSRS-memory pitch tied to anime emotion, not product feature
4. JLPT_CTAS — communicate "words that stick without grinding" as a feeling, not a feature
5. HASHTAG_POOLS — add a pool with niche discoverability tags (#AnimeStudy, #NihongoStudy, #JapaneseAnime)

Rules:
• old_text must be an EXACT verbatim substring of the file (copy-paste, no paraphrase)
• new_text must be clearly better — stronger hooks, sharper CTAs, better hashtags
• Each change must improve at least one quality OR relevance dimension

Return ONLY a valid JSON array, no prose, no fences:
[{"description":"what this improves","file":"scripts/social/generate-social-queue.ts","old_text":"...exact text...","new_text":"...improved text..."}]`,
    }],
  });

  const text = msg.content[0].type === "text" ? msg.content[0].text : "[]";
  return parseJson<Change[]>(text, []);
}

// ─── Agent 5: Implement ───────────────────────────────────────────────────────

function implement(changes: Change[]): number {
  const cache = new Map<string, string>();

  const read = (f: string): string => {
    if (!cache.has(f)) cache.set(f, readFileSync(join(ROOT, f), "utf8"));
    return cache.get(f)!;
  };

  let applied = 0;
  for (const c of changes) {
    const before = read(c.file);
    if (before.includes(c.old_text)) {
      cache.set(c.file, before.replace(c.old_text, c.new_text));
      console.log(`    ✓ ${c.description}`);
      applied++;
    } else {
      // Try trimmed match (trailing-whitespace drift)
      const trimmed = before.replace(/[ \t]+\n/g, "\n");
      const trimmedOld = c.old_text.replace(/[ \t]+\n/g, "\n");
      if (trimmed.includes(trimmedOld)) {
        cache.set(c.file, trimmed.replace(trimmedOld, c.new_text));
        console.log(`    ✓ ${c.description} (whitespace-trimmed match)`);
        applied++;
      } else {
        console.log(`    ✗ skipped (text not found): ${c.description.slice(0, 70)}`);
      }
    }
  }

  for (const [f, content] of cache) {
    writeFileSync(join(ROOT, f), content);
  }

  return applied;
}

// ─── Orchestrator ─────────────────────────────────────────────────────────────

async function main() {
  console.log("\n🦊  KitsuBeat — Instagram Reels Quality Loop");
  console.log(`    Quality target  : >${QUALITY_MIN}  |  Relevance target: >${RELEVANCE_MIN}`);
  console.log(`    Max iterations  : ${MAX_ITER}\n`);

  let lastQ = 0;
  let lastR = 0;

  for (let iter = 1; iter <= MAX_ITER; iter++) {
    console.log(`\n${"━".repeat(55)}`);
    console.log(`  Iteration ${iter} of ${MAX_ITER}`);
    console.log("━".repeat(55));

    // ── 1. Sample ──
    const posts = samplePosts();

    // ── 2. Quality ──
    process.stdout.write("  [quality]   grading… ");
    const q = await gradeQuality(posts);
    lastQ = q.total;
    console.log(`${q.total}/10`);
    console.log(`              breakdown: ${JSON.stringify(q.breakdown)}`);
    if (q.weaknesses.length) console.log(`              weaknesses: ${q.weaknesses.slice(0, 2).join(" | ")}`);

    // ── 3. Relevance ──
    process.stdout.write("  [relevance] grading… ");
    const r = await gradeRelevance(posts);
    lastR = r.total;
    console.log(`${r.total}/10`);
    console.log(`              breakdown: ${JSON.stringify(r.breakdown)}`);
    if (r.gaps?.length) console.log(`              gaps: ${r.gaps.slice(0, 2).join(" | ")}`);

    // ── Check thresholds ──
    if (q.total > QUALITY_MIN && r.total > RELEVANCE_MIN) {
      console.log(`\n✅  Both targets met — quality=${q.total}  relevance=${r.total}`);
      console.log("\nQuality strengths :");
      q.strengths.forEach(s => console.log(`  • ${s}`));
      console.log("\nRelevance strengths:");
      r.strengths.forEach(s => console.log(`  • ${s}`));
      break;
    }

    if (iter === MAX_ITER) {
      console.log(`\n⚠   Max iterations reached — quality=${lastQ}  relevance=${lastR}`);
      break;
    }

    const qGap = Math.max(0, QUALITY_MIN - q.total).toFixed(1);
    const rGap = Math.max(0, RELEVANCE_MIN - r.total).toFixed(1);
    console.log(`\n  → quality needs +${qGap}  |  relevance needs +${rGap}`);

    // ── 4. Improve ──
    process.stdout.write("  [improve]   synthesising… ");
    const changes = await synthesise(q, r, posts);
    console.log(`${changes.length} change(s) proposed`);

    // ── 5. Implement ──
    console.log("  [implement]");
    const applied = implement(changes);
    console.log(`              ${applied}/${changes.length} applied`);

    if (applied > 0) {
      // Re-generate X/Twitter queue so next iteration samples the updated templates
      process.stdout.write("  [regen]     regenerating social queue… ");
      try {
        execSync(
          "npx tsx --tsconfig tsconfig.scripts.json scripts/social/generate-social-queue.ts",
          { cwd: ROOT, stdio: "pipe" }
        );
        console.log("done");
      } catch (err) {
        console.log("⚠  generator failed — check generate-social-queue.ts for syntax errors");
        const errMsg = err instanceof Error ? err.message : String(err);
        console.log("  ", errMsg.slice(0, 300));
      }
    }
  }

  console.log(`\n${"═".repeat(55)}`);
  console.log(`  Final scores — quality: ${lastQ}/10  |  relevance: ${lastR}/10`);
  console.log("═".repeat(55) + "\n");
}

main().catch(console.error);
