/**
 * AiBadge — Phase 18 EU AI Act disclosure label.
 *
 * Renders an inline "AI-assisted" or "AI transcript (WhisperX)" text badge.
 * No "use client" — pure HTML span; works in RSC and client components.
 *
 * REQ-AI-LESSON-02, REQ-AI-LESSON-03, REQ-AI-LESSON-04,
 * REQ-AI-WHISPER-01, REQ-AI-WHISPER-02
 */

interface AiBadgeProps {
  /** Visible label text. Default: "AI-assisted". */
  label?: string;
  /** Extra Tailwind classes forwarded to the root <span>. */
  className?: string;
}

export function AiBadge({ label = "AI-assisted", className }: AiBadgeProps) {
  return (
    <span
      className={`inline-flex items-center gap-1 text-sm font-medium text-[var(--color-text-dim)] opacity-60 ${className ?? ""}`}
      aria-label={
        label === "AI transcript (WhisperX)"
          ? "AI transcript generated by WhisperX speech recognition"
          : "AI-assisted — generated by artificial intelligence"
      }
    >
      {label}
    </span>
  );
}
